# Site settings
title: Alan Plotko
email: me@alanplotko.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alanplotko.github.io/portfolio-blog/" # the base hostname & protocol for your site
twitter_username: alanplotko
github_username:  alanplotko

# Build settings
markdown: kramdown
