# Site settings
title: Alan Plotko
email: me@alanplotko.com
description: ""
baseurl: "/portfolio-blog" # the subpath of your site, e.g. /blog/
url: "https://alanplotko.github.io" # the base hostname & protocol for your site
twitter_username: alanplotko
github_username:  alanplotko

# Build settings
markdown: kramdown

highlighter: pygments
timezone: America/New_York
encoding: utf-8
safe: true
lsi: false