# Site settings
title: Alan Plotko
email: me@alanplotko.com
description: ""
url: "http://dev.alanplotko.com"
twitter_username: alanplotko
github_username:  alanplotko
timezone: America/New_York
encoding: utf-8
permalink: /:categories/:title

# Build settings
markdown: kramdown
highlighter: pygments

# Site navigation
navigation:
- text: Home
  url: /index.html
- text: About
  url: /about/
- text: Projects
  url: /projects/
- text: Resume
  url: /files/resume.pdf
- text: Blog
  url: /blog/

# Blog pagination
paginate: 3
paginate_path: "blog/page/:num/"