exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - reports/
  - package.json
  - yarn.lock
  - README.md
include:
  - .nojekyll
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
defaults:
  - scope:
      path: assets/**
    values:
      sitemap: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: text
    css_class: highlight
permalink: /blog/:slug
title: Alan Plotko
tagline: Blog
description: A software engineer who enjoys building cool stuff
url: https://www.alanplotko.com
baseurl: /
author:
  name: Alan Plotko
  url: https://www.alanplotko.com
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 5
  permalink: /page/:num/
  title: ':title - Page :num'
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: index
google_analytics: UA-104911692-1
