# Site settings
title: Alan Plotko
email: me@alanplotko.com
description: ""
url: "http://dev.alanplotko.com"
twitter_username: alanplotko
github_username:  alanplotko
timezone: America/New_York
encoding: utf-8

# Build settings
markdown: kramdown
highlighter: pygments