# Site settings
title: Alan Plotko
email: me@alanplotko.com
description: ""
url: "http://dev.alanplotko.com"
twitter_username: alanplotko
github_username:  alanplotko
timezone: America/New_York
encoding: utf-8
permalink: /:categories/:title

# Build settings
markdown: kramdown
highlighter: pygments

# Site navigation
navigation:
- text: About
  url: /about/
- text: Portfolio
  url: /portfolio/
- text: Resume
  url: /files/resume.pdf
- text: Blog
  url: /blog/
- text: Contact
  url: /contact/

# Blog pagination
paginate: 6
paginate_path: "blog/page/:num/"