# Site settings
title: Alan Plotko
email: me@alanplotko.com
description: ""
baseurl: "https://alanplotko.github.io/portfolio-blog"
twitter_username: alanplotko
github_username:  alanplotko

# Build settings
markdown: kramdown

highlighter: pygments
timezone: America/New_York
encoding: utf-8
safe: true
lsi: false