url: http://localhost:4000
author:
  url: http://localhost:4000
serviceWorker: false
clapAPI: http://localhost:8787
staticman:
  endpoint: http://localhost:8500/v3/entry/github/alanplotko/alanplotko.github.io/develop-blog/comments