# Author metadata
url:              https://www.alanplotko.com
author:
  url:            https://www.alanplotko.com

# Origins
events_origin: https://events.alanplotko.com
comments_origin: https://comments.alanplotko.com
api_origin: https://api.alanplotko.com

# Enable all
service_worker_enabled: true
comments_enabled: true
events_enabled: true