# Google Analytics
google_analytics: UA-104911692-1
api:
  worker: https://worker.alanplotko.com
  staticman:
    endpoint: https://comments.alanplotko.com/v3/entry/github/alanplotko/alanplotko.github.io/master/comments
