name: Build Jekyll and Deploy

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn prod

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./_site
