name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Run production build
      run: yarn prod

    - name: Deploy to gh-pages
      run: |
        DEST="_site"
        REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        BRANCH="gh-pages"

        echo "Publishing..."

        cd ${DEST}

        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "Published by GitHub Actions"
        git push --force ${REPO} master:${BRANCH}
